#!/bin/sh

ssh_rekey() {
    ssh-keygen -R "$1"
    ssh -o StrictHostKeyChecking=no "$1"
}

lvresize_xfs() {
    if [ $# -lt 2 ]
    then
        echo "usage: $0 <size> <device> [args]"
        return 1
    fi

    size=$1
    device=$2

    shift 2

    sudo lvresize -L "$size" "$@" "$device"
    sudo xfs_growfs "$device"
}

lskernel() {
    sudo dnf list installed | grep kernel.x86_64
}

rmkernel() {
    sudo dnf remove \
        "kernel-$1" \
        "kernel-core-$1" \
        "kernel-devel-$1" \
        "kernel-modules-$1" \
        "kernel-modules-extra-$1"
}

mkcd() {
    mkdir -p "$1" && cd "$1" || exit
}
